### PR TITLE
Highlight toc section on scroll

### PR DESCRIPTION
**Pull request by dispatchrabbi**
I still want to zhuzh the spacing on the nav items. But the JS is good, I think.

### CODE REVIEW

**Comment by cajunluke** [comment]
lgtm; I agree the spacing needs tweaking

I was thinking it might be nice to highlight the whole h1 section and the h2 section the user is in, like this:
Screen Shot 2021-03-08 at 23 51 15
Then it might be easier to see where the selection is when scrolling the left panel if the selection was offscreen

**Comment by dispatchrabbi** [comment]
> lgtm; I agree the spacing needs tweaking
> 
> I was thinking it might be nice to highlight the whole h1 section and the h2 section the user is in, like this:
> Screen Shot 2021-03-08 at 23 51 15
> Then it might be easier to see where the selection is when scrolling the left panel if the selection was offscreen

I tried this and wasn't a fan of the effect. I also tried scrolling the current section onto the screen and it was pretty jerky. I think I'm good with how it is here.

**Comment by dispatchrabbi** [comment]
This is no longer WIP; does it look good to you @cajunluke?

**Comment by cajunluke** [comment]
lgtm

**Review by cajunluke — APPROVED** [review]

**Pull request merged**
